app_client:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
app_server:
    resource: "@AppBundle/Resources/config/routing.yml"
    type: rest
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
pai_parcel:
    type: rest
    prefix: /api
    resource: "@AppBundle/Resources/config/routing.yml"
pai_parcel_order:
    type: rest
    prefix: /po
    resource: "@AppBundle/Resources/config/routing.yml"
parcelorder_angular:
    resource: "@AppBundle/Controller"
    type: annotation