postmen:
    type: rest
    resource: AppBundle\Controller\PostmenController

parcel_order:
    type: rest
    resource: AppBundle\Controller\ParcelOrderController

task:
    type: rest
    resource: AppBundle\Controller\TaskController

mobilepost:
    type: annotation
    resource: AppBundle\Controller\DefaultController